### PR TITLE
[Helm] Add mechanism to automatically restart pods on upgrade

### PR DESCRIPTION
**Pull request by i5okie**
- Added annotations to deployments with checksums for relevant configmaps and secrets

### CODE REVIEW

**Review by esune — CHANGES_REQUESTED** [review]
Can we remove the `values-test.yaml` and `values-production.yaml` altogether since configurations for those environments are stored elsewhere?

Other than that, changes look good - it will be great to not have to kick the pods every time 😎

**Comment by loneil** [comment]
> Can we remove the values-test.yaml and values-production.yaml altogether since configurations for those environments are stored elsewhere?

Maybe out of touch on this, but where are we storing those then?

**Comment by esune** [comment]
> > Can we remove the values-test.yaml and values-production.yaml altogether since configurations for those environments are stored elsewhere?
> 
> Maybe out of touch on this, but where are we storing those then?

https://github.com/bcgov/trust-over-ip-configurations/tree/main/helm-values

**Comment by i5okie** [comment]
> > > Can we remove the values-test.yaml and values-production.yaml altogether since configurations for those environments are stored elsewhere?
> > 
> > 
> > Maybe out of touch on this, but where are we storing those then?
> 
> https://github.com/bcgov/trust-over-ip-configurations/tree/main/helm-values

Should we also remove the [Promote Instance](https://github.com/bcgov/traction/blob/main/.github/workflows/on_push_tag.yaml) workflow?

**Review by esune — APPROVED** [review]
👍🏻

**Pull request merged**
