### PR TITLE
Create schemas 2 327

### PR DESCRIPTION
**Pull request by popkinj**
Page and UI component for creating a new schema.

### CODE REVIEW

**Review by Jsyro — COMMENTED** [review]
Component Structure looks good, can you share a view screen shots of it in action?

**Comment by popkinj** [comment]
> 

Yeah, great idea.

**Review by Jsyro — APPROVED** [review]
image

Thanks for the image. The dropdown is a different size than the textbox, but that will all need to be revisited when are start styling this.

**Comment by popkinj** [comment]
Yeah... I spent very little time in CSS land.

**Pull request merged**
