### PR TITLE
Bringing back old attributes into the reservations model

### PR DESCRIPTION
**Pull request by popkinj**
Short term fix for API errors. 
Unable to duplicate error locally. I'm hoping test more thoroughly with the deployed PR.

### CODE REVIEW

**Comment by popkinj** [comment]
Everything seem to work here. However, the DB obviously doesn't have any of the older data.
All the old attributes have be re-introduced to the reservation modal. However, I don't see them in the payload for the Innkeeper table. Is this a possible issue???
Screenshot from 2023-09-15 14-33-02

**Comment by loneil** [comment]
> Everything seem to work here. However, the DB obviously doesn't have any of the older data. All the old attributes have be re-introduced to the reservation modal. However, I don't see them in the payload for the Innkeeper table. Is this a possible issue??? 
If they're empty, which they would be on a new reservation they wouldn't come back in the response, right? I think that's how it works.

**Comment by popkinj** [comment]
> > Everything seem to work here. However, the DB obviously doesn't have any of the older data. All the old attributes have be re-introduced to the reservation modal. However, I don't see them in the payload for the Innkeeper table. Is this a possible issue???
> 
> If they're empty, which they would be on a new reservation they wouldn't come back in the response, right? I think that's how it works.

Ah.... That makes sense.

**Comment by esune** [comment]
@loneil @popkinj if this is ready to go please merge, don't wait on me

**Review by loneil — APPROVED** [review]

**Pull request merged**
