### PR TITLE
[Feature] Enable SMTP Authentication in Tenant UI

### PR DESCRIPTION
**Pull request by i5okie**
## Enable using authentication with SMTP

Nodemailer used in Tenant UI supports using authentication. This PR extends the code to allow setting `secure`, and providing `user` and `password` variables via the Helm values. 

_For additional information refer to the `nodemailer` documentation: https://nodemailer.com/smtp/#authentication_

Thanks @loneil for your help!

### CODE REVIEW

**Comment by loneil** [comment]
To test this on the deployed PR we can temporarily set `reservation.auto_approve` in from `plugin-config.yml` in the config-map to false (or update it in values-pr to false and redeploy). Then reservation requests on the PR will send emails.

Can test out when deployment goes through but looking at code it seems ok. Probably good global setting to have though don't think we'll ever need this as we'd likely always be using the gov smtp server in OCP where it doesn't need auth?

**Review by esune — APPROVED** [review]
Looks good assuming the testing with no auth credentials yields positive results. @loneil it's true that for BCGov OCP we would not need the auth credentials, but it's nice to have the option 😉

**Comment by i5okie** [comment]
Works. Tested with `reservation.auto_approve` set to false as per @loneil's comment.

**Review by loneil — APPROVED** [review]
Looks good! Tried out locally on VPN with secure false to confirm emails send

**Pull request merged**
