### PR TITLE
Adding icons is important for mobile layout

### PR DESCRIPTION
**Pull request by popkinj**
Hey @GurcharanjeetSingh . 
What are your thoughts on these new icons in the dropdown?

I also added a little documentation in the code describing that the icons are mandatory for mobile layout.

Signed-off-by: Jamie Popkin <popkinj@littleearth.ca>
Screenshot from 2023-02-07 12-27-14
Screenshot from 2023-02-07 12-27-06

### CODE REVIEW

**Comment by GurcharanjeetSingh** [comment]
> Hey @GurcharanjeetSingh . What are your thoughts on these new icons in the dropdown?
> 
> I also added a little documentation in the code describing that the icons are mandatory for mobile layout.
> 
> Signed-off-by: Jamie Popkin [popkinj@littleearth.ca](mailto:popkinj@littleearth.ca) Screenshot from 2023-02-07 12-27-14 Screenshot from 2023-02-07 12-27-06

Hey Jamie,
I am confused with the menu and sub-menu names i.e. Connections; because of the repetition. The icon is good for the invitations but for the connections we can have the same icon of the main menu i.e. the 2 person icon.

**Comment by popkinj** [comment]
> 

Sounds good @GurcharanjeetSingh . I'll switch icons.

**Comment by popkinj** [comment]
Screenshot from 2023-02-07 13-03-58

**Comment by GurcharanjeetSingh** [comment]
> Screenshot from 2023-02-07 13-03-58

Looks good. Thank you!

**Review by loneil — APPROVED** [review]

**Pull request merged**
