### PR TITLE
Jest 454

### PR DESCRIPTION
**Pull request by popkinj**
## Very Minimal Installation and config of Jest
```bash
cd traction/services/tenant-ui
npm test
```
This is working with a placeholder test.
Reports out code coverage.

### CODE REVIEW

**Review by loneil — CHANGES_REQUESTED** [review]
Couple things missing. We'll need coverage reporting (jest config `collectCoverageFrom`)

image

Which will need the `ts-jest` preset. See for example https://about.codecov.io/blog/measuring-typescript-code-coverage-with-jest-and-github-actions/

**Comment by popkinj** [comment]
Screenshot from 2023-04-18 09-13-49

**Comment by loneil** [comment]
Tenant for testing PR deployment if needed

eb0a70ba-7cb7-4881-94bf-774a57810907
322c88ed-871b-4386-8e1d-249767206134

**Comment by loneil** [comment]
Fixed deployment issue. Dist structure was being different due to addition of tests folder and jest ts config file at top level. (when it was **just** `src` at top level with TS files that defaulted to `/dist`). Changed to not include non `src` stuff in built dist.
https://github.com/bcgov/traction/pull/548/commits/22277b4f415b536a6806f98bc539992cb5f131f0

**Review by loneil — APPROVED** [review]

**Pull request merged**
