### PR TITLE
Feature/disable inaccessible buttons

### PR DESCRIPTION
**Pull request by Jsyro**
Disable buttons that require the tenant to be an issuer. 

image

image

Button behaviour/look is unchanged when tenant is an issuer.

### CODE REVIEW

**Review by loneil — COMMENTED** [review]
A few lint warnings
image

**Review by loneil — CHANGES_REQUESTED** [review]
My test tenant (TEST env) is an issuer and I've issued but the button is disabling on this branch

image

image

**Review by loneil — APPROVED** [review]
Works for me now

**Comment by Jsyro** [comment]
messed up the rebase, redoing in new branch.

**Pull request closed without merging**
