### PR TITLE
Use /ledger/register-nym endpoint

### LINKED ISSUE #513: Update Tenant Public DID procedure
Remove the custom API call `/tenant/register-public-did` and replace with the built-in `/ledger/register-nym`. 

This will affect both the plugin and the tenant-ui.

### PR DESCRIPTION
**Pull request by usingtechnology**
Remove the custom innkeeper/tenant plugin endpoint and use the one provided by Aca-Py.

It's preferable to stick with raw Aca-Py where possible.

Closes #513

### CODE REVIEW

**Review by popkinj — APPROVED** [review]
Looks good. :+1:

**Comment by loneil** [comment]
Getting a 404 on Register public DID in this PR

image

**Comment by loneil** [comment]
@usingtechnology I see this when trying as well (above the 403)

```
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy_vdr.py", line 1350, in txn_endorse
raise BadLedgerRequestError("Cannot endorse invalid request") from err
aries_cloudagent.ledger.error.BadLedgerRequestError: Cannot endorse invalid request
2023-03-24 20:15:49,234 aries_cloudagent.core.conductor ERROR DON'T shutdown on BadLedgerRequestError Cannot endorse invalid request
2023-03-24 20:15:49,234 aries_cloudagent.core.dispatcher ERROR Handler error: Dispatcher.handle_message
Traceback (most recent call last):
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy_vdr.py", line 1348, in txn_endorse
request = ledger.build_custom_request(request_json)
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy_vdr/ledger.py", line 159, in build_custom_request
do_call("indy_vdr_build_custom_request", body_p, byref(handle))
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy_vdr/bindings.py", line 132, in do_call
raise get_current_error(True)
**indy_vdr.error.VdrError: Invalid request JSON: protocolVersion not found**
```

**Comment by usingtechnology** [comment]
> @usingtechnology I see this when trying as well (above the 403)
> 
> ```
> File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy_vdr.py", line 1350, in txn_endorse
> raise BadLedgerRequestError("Cannot endorse invalid request") from err
> aries_cloudagent.ledger.error.BadLedgerRequestError: Cannot endorse invalid request
> 2023-03-24 20:15:49,234 aries_cloudagent.core.conductor ERROR DON'T shutdown on BadLedgerRequestError Cannot endorse invalid request
> 2023-03-24 20:15:49,234 aries_cloudagent.core.dispatcher ERROR Handler error: Dispatcher.handle_message
> Traceback (most recent call last):
> File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/ledger/indy_vdr.py", line 1348, in txn_endorse
> request = ledger.build_custom_request(request_json)
> File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy_vdr/ledger.py", line 159, in build_custom_request
> do_call("indy_vdr_build_custom_request", body_p, byref(handle))
> File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/indy_vdr/bindings.py", line 132, in do_call
> raise get_current_error(True)
> indy_vdr.error.VdrError: Invalid request JSON: protocolVersion not found
> ```
> 
> **Invalid request JSON: protocolVersion not found**

good catch. ran into this error a lot when I was testing out multi-ledger. will have to look over notes etc to get more of a lead on this. quite possible that the endorser needs to have some configuration updated. sigh.

**Review by loneil — APPROVED** [review]
Working all good now

**Pull request merged**
