### PR TITLE
Update app version in charts

### PR DESCRIPTION
**Pull request by esune**
Prepare for 0.3.3 release

### CODE REVIEW

**Comment by loneil** [comment]
Getting an error pulling the image?
`Failed to pull image "ghcr.io/bcgov/traction-tenant-proxy:0.3.3": rpc error: code = Unknown desc = reading manifest 0.3.3 in ghcr.io/bcgov/traction-tenant-proxy: manifest unknown`

**Comment by loneil** [comment]
Added gross hardcoded values for now

**Comment by esune** [comment]
@loneil reverting the hardcoded changes - I should have put this in draft mode as I had not yet clicked on the "release" button.
Publishing is happening now.

**Comment by esune** [comment]
@loneil it should be ready for review again

**Review by loneil — APPROVED** [review]

**Pull request merged**
