### PR TITLE
chore: remove demos

### PR DESCRIPTION
**Pull request by amanji**
Demos have been migrated to [Aries ACA-Py Controllers](https://github.com/hyperledger/aries-acapy-controllers)

### CODE REVIEW

**Comment by amanji** [comment]
Resolves #1252

**Comment by usingtechnology** [comment]
Hey @amanji  - I am no longer a contributor / reviewer for this project. Cheers!

**Comment by amanji** [comment]
@usingtechnology Sorry about that. Meant to tag someone else and clicked by accident.

**Comment by usingtechnology** [comment]
figured as much, just didn't want to block you. but I see there are other reviewers anyway.

**Review by loneil — APPROVED** [review]
Sounds good

**Pull request merged**
