### PR TITLE
Adding workflow to delete ghcr images older than 30 days and closed PR

### PR DESCRIPTION
**Pull request by rajpalc7**
Resolves: https://github.com/bcgov/traction/issues/598 . Hi @esune , I have address all the minor tweaks that we discussed here https://github.com/bcgov/traction/pull/924 . Adding wade and ivan as reviewers

### CODE REVIEW

**Review by esune — APPROVED** [review]
I think this looks good now 👍🏻

**Review by esune — CHANGES_REQUESTED** [review]
Actually, you will need to fix DCO on your first commit @rajpalc7 as this is preventing the checks form passing.

**Comment by rajpalc7** [comment]
@esune - all test are passing now

**Comment by esune** [comment]
> @esune - all test are passing now

It looks like the commit is NOT signed, the check was manually set to pass. Please amend it to include DCO - https://github.com/bcgov/traction/pull/934/commits/6c9dd9c3958cc836c773fb9f36af587d48d13f8e

**Comment by rajpalc7** [comment]
@esune : fixed that now and squashed into 1 single commit.

**Review by esune — APPROVED** [review]

**Pull request merged**
