### PR TITLE
Reservation status and check-in

### PR DESCRIPTION
**Pull request by loneil**

### CODE REVIEW

**Review by popkinj — COMMENTED** [review]
Looks good. Like that you found a replacement for the embedded svg.

**Comment by loneil** [comment]
> Looks good. Like that you found a replacement for the embedded svg.

No need for images when they're primevue icons.

**Comment by popkinj** [comment]
> 

I used the svg because it was the closest thing I could find to the mockup... But I think it's probably better to stick with our existing fontset.

**Comment by loneil** [comment]
> > 
> 
> I used the svg because it was the closest thing I could find to the mockup... But I think it's probably better to stick with our existing fontset.

The icon images in the mockups are primevue icons. We use those so we don't have to add images. The one used by Guru here https://xd.adobe.com/view/04d57e67-4b0a-49c7-bf15-ea74939aa66e-5186/screen/460d9770-1a22-449a-a3ed-d5ab95db5917/ is the `pi-check-circle` from the iconset https://www.primefaces.org/primevue/icons

**Pull request merged**
